import { FunctionComponent } from "react";

const Head: FunctionComponent = () => {
  return (
    <>
      <title>Whop powered Application</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
};

export default Head;
