import { UserProps } from "@/lib/get-user-server-side";
import { NextPage } from "next";
import { signIn, signOut } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "../../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const Page: NextPage<UserProps> = ({ user }) => {
  return (
    <>
      <Head>
        <title>Whop powered application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <a
            href="/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <span>&lt;-</span> Go back
          </a>
          <p>
            Edit this page inside of{" "}
            <code className={styles.code}>pages/ssr/index.tsx</code>
          </p>
        </div>

        <div className={styles.center}>
          <div className={styles.otherbox}>
            <h1
              className={inter.className}
              style={{
                paddingLeft: "5px",
              }}
            >
              Welcome to{" "}
              <Link
                target="_blank"
                rel="noopener noreferrer"
                href="https://dash.whop.com?utm_source=nextjs-template"
              >
                Whop{user ? `, ${user.username}!` : `!`}
              </Link>
            </h1>
            <p
              className={inter.className}
              style={{
                paddingTop: "20px",
                paddingLeft: "5px",
              }}
            >
              This page could be your homepage before a user accesses your
              application, and this state is meant to represent a user who is{" "}
              <b>{user ? "logged in" : "logged out"}. </b> <br></br>
            </p>
            <div
              style={{
                paddingTop: "20px",
              }}
            >
              {user ? (
                <p style={{ textAlign: "center" }} className={styles.card}>
                  Logged in user object:{" "}
                  <code>{JSON.stringify(user, null, "\t")}</code>
                </p>
              ) : (
                <></>
              )}
            </div>
          </div>
        </div>
        <div>
          {!user ? (
            <div
              className={styles.grid}
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
              }}
            >
              <Link
                href="#"
                onClick={() => signIn("whop")}
                className={styles.card}
              >
                <h2 className={inter.className}>Login &rarr;</h2>
                <p className={inter.className}>Proceed to sign in with Whop</p>
              </Link>
            </div>
          ) : (
            <div
              className={styles.grid}
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
              }}
            >
              <Link href="#" onClick={() => signOut()} className={styles.card}>
                <h2 className={inter.className}>&larr; Logout </h2>
                <p className={inter.className}>
                  This is an SSR gating of your application.
                </p>
              </Link>
              <Link href="/ssr/product-gated" className={styles.card}>
                <h2 className={inter.className}>Application (SSR) &rarr;</h2>
                <p className={inter.className}>
                  This is an SSR gating of your application.
                </p>
              </Link>
              <Link href="/ssg/product-gated" className={styles.card}>
                <h2 className={inter.className}>Application (SSG)&rarr;</h2>
                <p className={inter.className}>
                  This is an SSG gating of your application.
                </p>
              </Link>
            </div>
          )}
        </div>
      </main>
    </>
  );
};

export default Page;

export { default as getServerSideProps } from "@/lib/get-user-server-side";
