import { UserProps } from "@/lib/get-user-server-side";
import { NextPage } from "next";
import { signIn, signOut } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../styles/Home.module.css";

const Page: NextPage<UserProps> = ({ user }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Paywall App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <Link
            target="_blank"
            rel="noopener noreferrer"
            href="https://dash.whop.com"
          >
            Whop!
          </Link>
        </h1>
        <p className={styles.description}>
          This page could be your homepage before a user accesses your
          application, and this state is meant to represent a user who is{" "}
          <b>{user ? "logged in" : "logged out"}. </b>{" "}
          {user && (
            <Link
              href="#"
              style={{ textDecoration: "underline" }}
              onClick={() => signOut()}
            >
              Click here to logout
            </Link>
          )}
          <br></br>
          <br></br>You can edit this page in{" "}
          <code className={styles.code}>pages/ssr/index.tsx</code>
        </p>

        {!user ? (
          <div className={styles.grid}>
            <Link
              href="#"
              onClick={() => signIn("whop")}
              className={styles.card}
            >
              <h2>Login &rarr;</h2>
              <p>Proceed to sign in with Whop</p>
            </Link>
          </div>
        ) : (
          <>
            <p style={{ textAlign: "center" }}>
              Logged in user object: {JSON.stringify(user, null, 2)}
            </p>
            <div className={styles.grid}>
              <Link href="/ssr/pass-gated" className={styles.card}>
                <h2>Access Application &rarr;</h2>
                <p>This is an SSR gating of your application.</p>
              </Link>
              <Link href="/ssg/pass-gated" className={styles.card}>
                <h2>Access Application &rarr;</h2>
                <p>This is an SSG gating of your application.</p>
              </Link>
            </div>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <Link
          href="https://dash.whop.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/logo.svg" alt="Whop Logo" width={72} height={16} />
          </span>
        </Link>
      </footer>
    </div>
  );
};

export default Page;

export { default as getServerSideProps } from "@/lib/get-user-server-side";
