import { usePurchaseLink } from "@/lib/get-purchase-link";
import getSdk from "@/lib/get-user-sdk/pages";
import findPass from "@/lib/has-pass";
import ServerSDK from "@/lib/sdk";
import { AccessPass, Membership, Plan } from "@whop-sdk/core";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

/**
 * a list of pass IDs that are allowed to view this page
 */
const ALLOWED_PASS: string = process.env.NEXT_PUBLIC_REQUIRED_PASS || "";
/**
 * a plan that is recommended to buy if the user does not
 * own a required pass
 */
const RECOMMENDED_PLAN = process.env.NEXT_PUBLIC_RECOMMENDED_PLAN_ID || "";

type PassGatedProps =
  | {
      membership: Membership;
      pass: null;
      plan: null;
    }
  | {
      membership: null;
      pass: AccessPass;
      plan: Plan;
    };

const Page: NextPage<PassGatedProps> = ({ membership, pass, plan }) => {
  const link = usePurchaseLink(RECOMMENDED_PLAN);
  if (!membership) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Paywall App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Purchase <a href={link}>Access</a>
          </h1>
          <p className={styles.description}>
            This page is shown to a user who is signed in, but does not
            currently own an Access Pass.
            <br></br>
            <br></br>You can edit this page in{" "}
            <code className={styles.code}>pages/ssr/pass-gated.tsx</code>
          </p>
          <div className={styles.grid}>
            <a href={link} className={styles.card}>
              <h2>Buy Access &rarr;</h2>
              <p>Purchase via Whop.</p>
            </a>
          </div>
          <p style={{ textAlign: "center" }}>
            Required Pass to Own: {JSON.stringify({ pass }, null, 2)}
          </p>
          <p style={{ textAlign: "center" }}>
            Recommended Pricing Plan:{" "}
            <code>{JSON.stringify({ plan }, null, 2)}</code>
          </p>
          <p style={{ textAlign: "center" }}>User has membership: No</p>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://dash.whop.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image src="/logo.svg" alt="Whop Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Paywall App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Access <a href="#">Granted 🚀</a>
        </h1>
        <p className={styles.description}>
          This page is shown to a user who is signed in, and owns your required
          access pass!
          <br></br>
          <br></br>You can edit this page in{" "}
          <code className={styles.code}>pages/ssr/pass-gated.tsx</code>
        </p>
        <div className={styles.grid}>
          <a
            href={"https://whop.com/hub/" + membership.id}
            className={styles.card}
          >
            <h2>Customer Portal &rarr;</h2>
            <p>Manage your billing and access.</p>
          </a>

          <a
            href={"https://whop.com/hub/" + membership.id}
            className={styles.card}
          >
            <h2>Leave a review &rarr;</h2>
            <p>If you like this webapp, leave a review!</p>
          </a>
        </div>
        <p style={{ textAlign: "center" }}>User has membership: Yes!</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://dash.whop.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/logo.svg" alt="Whop Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Page;

/**
 * This first makes sure the user is logged in, redirecting them if they are not
 * and then checks if the user owns a membership specified in the ALLOWED_PASSES
 * array.
 */
export const getServerSideProps: GetServerSideProps<PassGatedProps> = async ({
  req,
  res,
}) => {
  const { sdk } = await getSdk(req, res);
  if (!sdk)
    return {
      redirect: {
        destination: "/ssr",
        permanent: false,
      },
    };
  const membership = await findPass(sdk, ALLOWED_PASS);
  if (membership)
    return {
      props: {
        membership,
        pass: null,
        plan: null,
      },
    };
  else {
    const [pass, plan] = await Promise.all([
      ServerSDK.accessPasses.retrieveAccessPass({
        id: ALLOWED_PASS,
      }),
      ServerSDK.plans.retrievePlan({
        id: RECOMMENDED_PLAN,
      }),
    ]);
    return {
      props: {
        membership: null,
        pass,
        plan,
      },
    };
  }
};
