import getSdk from "@/lib/get-user-sdk/app";
import findPass from "@/lib/has-pass";
import { NextAppPage } from "@/types/app-dir";
import Head from "next/head";
import Image from "next/image";
import styles from "../../../../styles/Home.module.css";

const ALLOWED_PASS: string = process.env.NEXT_PUBLIC_REQUIRED_PASS || "";

/**
 * The Layout of this level is pass-gated, which makes
 * and page child gated without extra configuration.
 */
const Page: NextAppPage = async () => {
  /**
   * get the sdk and membership again here, this is
   * only done to get the data and not to verify the user
   * owns the pass. if the user does not own the pass this
   * section will never be rendered as the layout already
   * verifies that the pass is owned.
   */
  const { sdk } = await getSdk();
  const membership = (await findPass(sdk!, ALLOWED_PASS))!;
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Paywall App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Access <a href="#">Granted 🚀</a>
          </h1>
          <p className={styles.description}>
            This page is shown to a user who is signed in, and owns your
            required access pass!
            <br></br>
            <br></br>You can edit this page in{" "}
            <code className={styles.code}>pages/ssr/pass-gated.tsx</code>
          </p>
          <div className={styles.grid}>
            <a
              href={"https://whop.com/hub/" + membership.id}
              className={styles.card}
            >
              <h2>Customer Portal &rarr;</h2>
              <p>Manage your billing and access.</p>
            </a>

            <a
              href={"https://whop.com/hub/" + membership.id}
              className={styles.card}
            >
              <h2>Leave a review &rarr;</h2>
              <p>If you like this webapp, leave a review!</p>
            </a>
          </div>
          <p style={{ textAlign: "center" }}>User has membership: Yes!</p>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://dash.whop.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image src="/logo.svg" alt="Whop Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
};

export default Page;
