import { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

/**
 * this page is gated on a middleware level
 */
const SSGProductGatedPage: NextPage = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Paywall App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.svg" />
        </Head>

        <main className={styles.main}>
          <div className={styles.description}>
            <a
              href="/ssr"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <span>&lt;-</span> Go back
            </a>
            <p>
              Edit this page inside of{" "}
              <code className={styles.code}>
                pages/ssg/product-gated/page.tsx
              </code>
            </p>
          </div>

          <div className={styles.center}>
            <div className={styles.otherbox}>
              <h1 className={inter.className}>Access Granted 🚀 (SSG)</h1>
              <p className={inter.className}>
                This page is protected by the middleware, so if no SSG bailouts
                are used here, the page will be statically served.
              </p>
            </div>
          </div>
        </main>
      </div>
    </>
  );
};

export default SSGProductGatedPage;
